title: kallakata.dev
description: "A Jekyll Blog Theme For Hackers"
# author:
#   name: "Pavel Vařenka"
#   email: "pavel.varenka@protonmail.com"
#   url: "https://linktr.ee/pavelvarenka"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

collections:
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "kallakata"
year : "2025"

author:
  avatar           : "mainpy.JPEG"
  name             : "Pavel Vařenka - @kallakata"
  pronouns         : "he/him"  
  bio              : "Platform Engineer, tinkerer, physics lover and avid Linux enthusiast"
  location         : "Cyberspace & occasionally Prague"
  employer         : "Veeam"
  uri              : "https://linktr.ee/pavelvarenka"
  email            : "pavel.varenka@protonmail.com" 

  arxiv            : 
  googlescholar    : 
  impactstory      : 
  orcid            : 
  semantic         : 
  pubmed           : 
  researchgate     : 
  scopus           : 

  bitbucket        : 
  codepen          : 
  dribbble         : 
  github           : "kallakata"
  kaggle           :   
  stackoverflow    : 

  bluesky          : "bsky.app"
  facebook         : 
  flickr           : 
  foursquare       : 
  goodreads        : 
  google_plus      : 
  keybase          : 
  instagram        : 
  lastfm           : 
  linkedin         : "https://www.linkedin.com/in/pavelvarenka/"
  mastodon         : "TBD"
  medium           : "https://medium.com/@pavel.varenka"
  pinterest        : 
  soundcloud       : 
  steam            : 
  telegram         : "https://t.me/kallakata"
  tumblr           : 
  twitter          : 
  vine             : 
  weibo            : 
  wikipedia        : 
  xing             : 
  youtube          : 
  zhihu            : 
